### ISSUE TITLE
Add "BMO Timeout Seconds" to Bugzilla Config

### ISSUE THREAD

**Issue by darkwing** [mozilla-services/phabricator-extensions#31]
We should add a value to `bugzilla/config/PhabricatorBugzillaConfigOptions.php`: `bugzilla.timeout`; this will be our timeout for all BMO requests.  At present it would be used in:

- The validator class here:  https://github.com/mozilla-services/phabricator-extensions/pull/26
- The author provider: https://github.com/mozilla-services/phabricator-extensions/blob/master/auth/PhabricatorBMOAuthProvider.php

**Comment by dklawren** [comment]
Moved to https://phabricator.services.mozilla.com/D5
